apiVersion: v2
name: radarr
description: Radarr is a movie collection manager for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new movies and will interface with clients and indexers to grab, sort, and rename them.
type: application
version: 0.1.8
appVersion: 6.0.4
keywords:
  - radarr
  - films
  - pvr
  - usenet
  - bittorrent
  - rss
home: https://brains-beyond-expectations.github.io/bbe-charts
icon: https://avatars.githubusercontent.com/u/25025331
sources:
  - https://github.com/Radarr/Radarr
