apiVersion: v2
name: prowlarr
description: Prowlarr is an indexer manager/proxy built on the popular *arr .net/reactjs base stack to integrate with your various PVR apps.
type: application
version: 0.1.7
appVersion: 2.1.5
keywords:
  - prowlarr
  - indexer
  - proxy
home: https://brains-beyond-expectations.github.io/bbe-charts
icon: https://avatars.githubusercontent.com/u/73049443
sources:
  - https://github.com/Prowlarr/Prowlarr
